version: "3"

services:
  nifi:
    image: apache/nifi:1.13.2
    ports:
      - 8080:8080
      - 8042:8042
    volumes:
      - ./nifi-drivers:/opt/nifi/nifi-current/drivers
      - ./nifi-conf:/opt/nifi/nifi-current/conf

  postgre_prod:
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: prod
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  postgre_ml:
    image: postgres:13.4-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ml
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
